const exerciseTypes = {getallenkennis:['Getallen gebruiken om te zeggen hoeveel er zijn',
'Getallen gebruiken in een rangorde',
'Getallen gebruiken bij een maateenheid',
'Getallen gebruiken in een bewerking',
'Getallen gebruiken als code',
'Honderdvelden',
'Getallenassen',
'We vergelijken en ordenen natuurlijke getallen',
'Duizendtal, honderdtal, tiental en eenheid',
'We structureren getallen',
'Tellen, terugtellen en doortellen per 1, per 2, per 5, per 10, per 50 of per 100',
'Patronen',
'Schatten',
'Afronden',
'Even getallen',
'Oneven getallen',
'Ik deel 18',
'Gemeenschappelijke delers',
'Kenmerken van deelbaarheid',
'Veelvouden',
'Breuken',
'De breukenladder',
'Stambreuken',
],
bewerkingen:[
'Ik ken rekentaal',
'Eigenschappen van en relaties tussen bewerkingen',
'Ik controleer met de omgekeerde bewerking',
'Hoofdrekenen',
'Maaltafels en de deeltafels/delingstafels',
'Hoofdrekenen met breuken',
'Schatten',
'Cijferen - Optellen',
'Cijferen - Aftrekken',
'Cijferen - Vermenigvuldigen',
'Cijferen - Delen',
],
meetkunde:[
'Meten door te vergelijken',
'Meten met natuurlijke maateenheden',
'Lengte',
'Inhoud',
'Gewicht',
'Tijd',
'Geldwaarden',
'Temperatuur'
],
meten_en_metend_rekenen:[
'We oriënteren ons ruimtelijk',
'Rechte lijnen',
'Oppervlakken',
'Vlakke figuren',
'Hoeken',
'Veelhoeken',
'Vierhoeken (vierkant, rechthoek, ruit, parallellogram en trapezium)',
'Diagonalen',
'Driehoeken',
'Symmetrie',
'Gelijkheid van vorm én van grootte',
'Schaduwbeelden',
'Kijklijnen of viseerlijnen',
'Patronen'
],
toepassingen:[
'Werkwijze (heuristiek)',
'Voorbeelden'
]};

export default exerciseTypes;