version: "3.9"
services:
  frontend:
    image: "maartenoste/wizzer-client"
    networks:
      - sub-etha
  backend:
    image: "maartenoste/wizzer-server"
    networks:
      - sub-etha
  reverseproxy:
    ports:
      - "80:80"
    image: maartenoste/reverseproxy
    networks:
      - sub-etha
networks:
  sub-etha: